"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 1500

[git_branch]
symbol = "🌱 "

[kubernetes]
disabled = false

[time]
disabled = false
use_12hr = true
time_format = '%I:%M %p'
