#!/bin/bash

echo "Setting up screenshots folder on desktop"
mkdir -p ~/Desktop/screenshots
defaults write com.apple.screencapture location ~/screenshots
defaults write com.apple.screencapture "location-last" ~/screenshots
killall SystemUIServer
