[settings]
experimental = true

[tools]
bun = ['latest']
clojure = ['latest'] 
dotnet = ['latest']
elixir = ['latest']
erlang = ['latest']
java = ['corretto']
lua = ['latest']
node = ['lts', 'latest']
perl = ['latest', 'system']
python = ['latest', '2', 'system']
ruby = ['latest', '2', 'system']
rust  = ['latest']
